import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { ChakraProvider } from "@chakra-ui/react"
import { ApolloProvider } from '@apollo/client'
import Nav from '../components/nav'
import Footer from '../components/footer';
import apolloClient from '../lib/apollo'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={apolloClient}>
      <ChakraProvider>
        <Head>
          <title>InLight App</title>
          <meta name="description" content="Generated by InLight App" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <Component {...pageProps} />
        <Footer />
      </ChakraProvider>
    </ApolloProvider>
    )
}

export default MyApp