import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Box, Flex } from '@chakra-ui/react';
import styles from '../styles/Home.module.css'
import Hero from '../components/hero';
import Nav from '../components/nav';
import Features from '../components/features';
import Statistics from '../components/statistics';
import Footer from '../components/footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Nav />
      <Head>
        <title>InLight App</title>
        <meta name="description" content="Generated by InLight App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Flex justifyContent="center" alignItems="center" direction="column">
        <Box maxWidth="1200px" my={12}>
          <Features />
        </Box>
        <Box maxWidth="1200px" my={12}>
          <Statistics />
        </Box>
      </Flex>
      <Footer />
    </div>
  )
}

export default Home
