import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/hero';
import Nav from '../components/nav';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Nav />
      <Head>
        <title>InLight App</title>
        <meta name="description" content="Generated by InLight App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          InLight App
        </h1>
      </main>
      <Hero />

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export default Home
